### PR TITLE
add large string test

### PR DESCRIPTION
**Pull request by complected**
and some formatting `test.js`.

### CODE REVIEW

**Comment by complected** [comment]
@nmushegian

**Comment by complected** [comment]
`test.js`'s runtime does increase from couple seconds to 5-6 seconds. Of course, devs can turn it off by commenting it out during dev time.

```

> coreword@0.0.3 test
> tsc && node ./core/test.js

TAP version 13
# Sign message and recover public key
# Differentially test against Ethers.js
# bad signature
ok 1 show throw
# 1:
ok 2 should be equivalent
# What is real? That which is irreplacable.:
ok 3 should be equivalent
# \n:
ok 4 should be equivalent
# "\\u0024":
ok 5 should be equivalent
# !@#$:
ok 6 should be equivalent
# α:
ok 7 should be equivalent
# ⛓️👷‍♂️🏙️👨‍👨‍👧‍👧:
ok 8 should be equivalent
# VERY LONG STRING:
ok 9 should be equivalent
# 1:
ok 10 should be equivalent
ok 11 should be equivalent
ok 12 should be equivalent
ok 13 should be equivalent
# What is real? That which is irreplacable.:
ok 14 should be equivalent
ok 15 should be equivalent
ok 16 should be equivalent
ok 17 should be equivalent
# \n:
ok 18 should be equivalent
ok 19 should be equivalent
ok 20 should be equivalent
ok 21 should be equivalent
# "\\u0024":
ok 22 should be equivalent
ok 23 should be equivalent
ok 24 should be equivalent
ok 25 should be equivalent
# !@#$:
ok 26 should be equivalent
ok 27 should be equivalent
ok 28 should be equivalent
ok 29 should be equivalent
# α:
ok 30 should be equivalent
ok 31 should be equivalent
ok 32 should be equivalent
ok 33 should be equivalent
# ⛓️👷‍♂️🏙️👨‍👨‍👧‍👧:
ok 34 should be equivalent
ok 35 should be equivalent
ok 36 should be equivalent
ok 37 should be equivalent
# VERY LONG STRING:
ok 38 should be equivalent
ok 39 should be equivalent
ok 40 should be equivalent
ok 41 should be equivalent

1..41
# tests 41
# pass  41

# ok

```

**Comment by nmushegian** [comment]
Since sign takes a hash now, all you are testing here is that hash works. Before, the reason to test would have been related to the type of the library, but now it doesn’t matter since we are taking the hash

**Comment by complected** [comment]
> now it doesn’t matter since we are taking the hash.

Got you, that's true.

**Pull request closed without merging**
